### ISSUE TITLE
Exeption in IntelliJ IDEA 2021.1

### ISSUE THREAD

**Issue by AlexandreLoub** [shiraji/emoji#33]
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'font' of com/intellij/util/ui/JBFont.create must not be null
	at com.intellij.util.ui.JBFont.$$$reportNull$$$0(JBFont.java)
	at com.intellij.util.ui.JBFont.create(JBFont.java)
	at com.intellij.util.ui.JBFont.label(JBFont.java:22)
	at com.intellij.util.IconUtil$1MyIcon.update(IconUtil.java:887)
	at com.intellij.util.IconUtil$1MyIcon.<init>(IconUtil.java:857)
	at com.intellij.util.IconUtil.textToIcon(IconUtil.java:905)
	at com.github.shiraji.emoji.action.EmojiPreloadingActivity$preload$callable$1.call(EmojiPreloadingActivity.kt:26)
	at com.github.shiraji.emoji.action.EmojiPreloadingActivity$preload$callable$1.call(EmojiPreloadingActivity.kt:14)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$1(ApplicationUtil.java:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:41)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Intelij config: 
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.13-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1890M
Cores: 12

**Comment by shiraji** [comment]
Could you provide minimum step to reproduce this problem? @AlexandreLoub

**Comment by AlexandreLoub** [comment]
This happens every time I launch IntelliJ IDEA
